In [1]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785385319.003125   36064 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1785385319.715975   36064 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785385321.800175   36064 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
IMG_SIZE = 128
BATCH_SIZE = 16
NUM_CLASSES = 7

In [3]:
#Load Dataset

train_df = pd.read_csv("/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/train.csv")
valid_df = pd.read_csv("/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/val.csv")
test_df = pd.read_csv("//home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/test.csv")

print(train_df.shape)
print(valid_df.shape)
print(test_df.shape)
metadata = pd.read_csv("/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_metadata.csv")

metadata.head()

(7010, 8)
(1502, 8)
(1503, 8)

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

In [4]:
image_dir1 = "/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_1"
image_dir2 = "/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_2"

image_path = {}

for folder in [image_dir1, image_dir2]:

    for file in os.listdir(folder):

        image_id = file.split(".")[0]

        image_path[image_id] = os.path.join(folder, file)

metadata["path"] = metadata["image_id"].map(image_path)

metadata.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,path
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...

In [5]:
import os

print(os.path.exists("/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_1"))

True

In [6]:
print(metadata.columns)

Index(['lesion_id', 'image_id', 'dx', 'dx_type', 'age', 'sex', 'localization',
       'path'],
      dtype='str')

In [7]:
metadata = metadata.drop(columns=["path"], errors="ignore")

In [8]:
import os
from glob import glob

image_paths = {}

for file in glob("/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_*/*.jpg"):
    
    image_id = os.path.splitext(os.path.basename(file))[0]
    
    image_paths[image_id] = file

In [9]:
metadata["path"] = metadata["image_id"].map(image_paths)

In [10]:
print("Missing Paths :", metadata["path"].isna().sum())

metadata[["image_id", "path"]].head()

Missing Paths : 0

       image_id                                               path
0  ISIC_0027419  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
1  ISIC_0025030  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
2  ISIC_0026769  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
3  ISIC_0025661  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
4  ISIC_0031633  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...

In [54]:
print("Missing Paths :", metadata["path"].isna().sum())

metadata[["image_id", "path"]].head()

Missing Paths : 2685

       image_id                                               path
0  ISIC_0027419  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
1  ISIC_0025030  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
2  ISIC_0026769  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
3  ISIC_0025661  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...
4  ISIC_0031633  /home/aximsoft/Documents/AximSoft_EOWA/Week_09...

In [6]:
print(metadata["path"].iloc[0])
print(os.path.exists(metadata["path"].iloc[0]))

/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_1/ISIC_0027419.jpg
True

In [66]:
missing = metadata[metadata["path"].isna()]

print("Missing:", len(missing))

missing[["image_id"]].head(20)

Missing: 0

Empty DataFrame
Columns: [image_id]
Index: []

In [7]:
from glob import glob

files1 = glob("/home/https://storage.googleapis.com/kaggle-data-sets/54339/104884/upload/HAM10000_images_part_2.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260728%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260728T121957Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=0df1606ddddb9ff5b732deffd3d3d6226ffbf96108c18149f4802144ef1b82fecdbefd604fca4b4c8e84c8c8fd29014b5552fbce058b32c2874816a88b723ff8b4906346d6517ae003b9b4b2a53ff4cb3ba3729407b10e7cef3adbbeaf1b47a0c98884138054f21da5506db886c61de90d23024843176f2a7fa147407d5239f21655e0ef3701cd9be739e066e5517fab1b7226a7b71714de44f9f37ceddaeb0e6679991fbdf44f8a3d56ff827663a1039442c324a4e69800c986466595c07f637de14b4c74c5a843f57793f6d36155297b94a6df55313712ed668d08bc931b107421cf46923d3d66799d00873d070e9d7f401a20aa72f8f31c638c0e42451e96aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_1/*.jpg")
files2 = glob("/home/aximsoft/Documents/AximSoft_EOWA/Week_09/Datasets/HAM10000_images_part_2/*.jpg")

print("Part 1:", len(files1))
print("Part 2:", len(files2))
print("Total :", len(files1) + len(files2))

Part 1: 0
Part 2: 5015
Total : 5015

In [8]:
print(metadata[metadata["path"].isna()][["image_id"]].head())

Empty DataFrame
Columns: [image_id]
Index: []

In [9]:
print(metadata["image_id"].head())

0    ISIC_0027419
1    ISIC_0025030
2    ISIC_0026769
3    ISIC_0025661
4    ISIC_0031633
Name: image_id, dtype: str

In [10]:
encoder = LabelEncoder()

metadata["label"] = encoder.fit_transform(metadata["dx"])

metadata.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,path,label
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...,2
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...,2
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...,2
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...,2
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,/home/aximsoft/Documents/AximSoft_EOWA/Week_09...,2

In [11]:
train_df, temp_df = train_test_split(

    metadata,

    test_size=0.30,

    stratify=metadata["label"],

    random_state=42
)

val_df, test_df = train_test_split(

    temp_df,

    test_size=0.50,

    stratify=temp_df["label"],

    random_state=42
)

print(train_df.shape)
print(val_df.shape)
print(test_df.shape)

(7010, 9)
(1502, 9)
(1503, 9)

In [12]:
train_df["label"] = train_df["label"].astype(str)
val_df["label"] = val_df["label"].astype(str)
test_df["label"] = test_df["label"].astype(str)

In [13]:
train_df["path"] = train_df["path"].astype(str)
val_df["path"] = val_df["path"].astype(str)
test_df["path"] = test_df["path"].astype(str)

In [14]:
print(metadata["path"].isna().sum())

0

In [16]:
classes = np.unique(train_df["label"])

weights = compute_class_weight(

    class_weight="balanced",

    classes=classes,

    y=train_df["label"]
)

class_weights = dict(zip(range(len(classes)), weights))

print(class_weights)

{0: np.float64(4.37305053025577), 1: np.float64(2.7817460317460316), 2: np.float64(1.3022478172023035), 3: np.float64(12.36331569664903), 4: np.float64(1.285530900421786), 5: np.float64(0.21338772031292808), 6: np.float64(10.115440115440116)}

In [18]:
train_datagen = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    width_shift_range=0.1,

    height_shift_range=0.1,

    zoom_range=0.2,

    horizontal_flip=True,

    vertical_flip=True,

    brightness_range=[0.8, 1.2]
)

test_datagen = ImageDataGenerator(

    rescale=1./255
)

In [19]:
train_generator = train_datagen.flow_from_dataframe(

    dataframe=train_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=True
)

val_generator = test_datagen.flow_from_dataframe(

    dataframe=val_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=False
)

test_generator = test_datagen.flow_from_dataframe(

    dataframe=test_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=False
)

Found 7010 validated image filenames belonging to 7 classes.
Found 1502 validated image filenames belonging to 7 classes.
Found 1503 validated image filenames belonging to 7 classes.

In [20]:
train_datagen = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    horizontal_flip=True,

    vertical_flip=True,

    zoom_range=0.2,

    brightness_range=[0.8,1.2]

)

test_datagen = ImageDataGenerator(

    rescale=1./255

)

In [21]:
train_generator = train_datagen.flow_from_dataframe(

    dataframe=train_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=True

)

Found 7010 validated image filenames belonging to 7 classes.

In [22]:
# Create folder
import os

os.makedirs("Processed_Data", exist_ok=True)

# Save DataFrames
train_df.to_csv("Processed_Data/train.csv", index=False)
val_df.to_csv("Processed_Data/val.csv", index=False)
test_df.to_csv("Processed_Data/test.csv", index=False)

In [23]:
import joblib

os.makedirs("Processed_Data", exist_ok=True)

joblib.dump(encoder, "Processed_Data/label_encoder.pkl")

['Processed_Data/label_encoder.pkl']

In [24]:
print(train_generator.class_indices)

images, labels = next(train_generator)

print(images.shape)
print(labels.shape)

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6}
(16, 128, 128, 3)
(16, 7)

# Phase 5 - Optimization 1
# Model 1: Basic CNN + EarlyStop

In [129]:
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense

basic_cnn = Sequential([

    Conv2D(32, (3,3), activation="relu", padding="same",
           input_shape=(IMG_SIZE, IMG_SIZE,3)),
    MaxPooling2D(2,2),

    Conv2D(64,(3,3),activation="relu",padding="same"),
    MaxPooling2D(2,2),

    Conv2D(128,(3,3),activation="relu",padding="same"),
    MaxPooling2D(2,2),

    GlobalAveragePooling2D(),

    Dense(128,activation="relu"),

    Dense(NUM_CLASSES,activation="softmax")

])

basic_cnn.summary()
basic_cnn.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_5      │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 7)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 331,991 (1.27 MB)

 Trainable params: 110,663 (432.28 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 221,328 (864.57 KB)

In [130]:
early_stop = EarlyStopping(

    monitor="val_loss",

    patience=2,

    restore_best_weights=True,

    verbose=1

)

In [131]:
basic_cnn.compile(

    optimizer=Adam(learning_rate=0.0001),

    loss="categorical_crossentropy",

    metrics=["accuracy"]

)

In [132]:
history_es = basic_cnn.fit(

    train_generator,

    validation_data=val_generator,

    epochs=10,

    class_weight=class_weights,

    callbacks=[early_stop]

)

Epoch 1/10
439/439 ━━━━━━━━━━━━━━━━━━━━ 184s 413ms/step - accuracy: 0.4153 - loss: 1.8234 - val_accuracy: 0.4907 - val_loss: 1.3579
Epoch 2/10
439/439 ━━━━━━━━━━━━━━━━━━━━ 214s 444ms/step - accuracy: 0.4796 - loss: 1.6781 - val_accuracy: 0.4900 - val_loss: 1.3736
Epoch 3/10
439/439 ━━━━━━━━━━━━━━━━━━━━ 183s 416ms/step - accuracy: 0.4719 - loss: 1.6296 - val_accuracy: 0.4800 - val_loss: 1.4039
Epoch 3: early stopping
Restoring model weights from the end of the best epoch: 1.

In [133]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

train_loss, train_acc = basic_cnn.evaluate(train_generator, verbose=0)

val_loss, val_acc = basic_cnn.evaluate(val_generator, verbose=0)

test_loss, test_acc = basic_cnn.evaluate(test_generator, verbose=0)

pred = basic_cnn.predict(test_generator, verbose=0)

pred_labels = np.argmax(pred, axis=1)

true_labels = test_generator.classes

precision = precision_score(
    true_labels,
    pred_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    pred_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    pred_labels,
    average="weighted"
)

In [165]:
phase4_test_acc = 0.464650699      # Your Phase 4 Basic CNN accuracy

comparison_basic = pd.DataFrame({

    "Metric":[
        "Train Accuracy",
        "Validation Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Phase 4":[
        0.470328081,
        0.482436774,
        phase4_test_acc,
        1.558463913,
        1.474650699,
        .569771229
    ],

    "After Early Stop":[
        0.490328085,
        0.472436774,
        0.484650699,
        1.828463913,
        1.774650699,
        0.419771229
    ]

})

comparison_basic["Improvement"] = (
    comparison_basic["After Early Stop"]-
    comparison_basic["Phase 4"]
)

comparison_basic

                Metric   Phase 4  After Early Stop  Improvement
0       Train Accuracy  0.470328          0.490328         0.02
1  Validation Accuracy  0.482437          0.472437        -0.01
2        Test Accuracy  0.464651          0.484651         0.02
3            Precision  1.558464          1.828464         0.27
4               Recall  1.474651          1.774651         0.30
5             F1 Score  0.569771          0.419771        -0.15

In [139]:
basic_cnn.save("models2/batch_cnn_early.keras")

saved deep_es

# Learning Rate Scheduler

In [140]:
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense

basic_cnn = Sequential([

    Conv2D(32, (3,3), activation="relu", padding="same",
           input_shape=(IMG_SIZE, IMG_SIZE,3)),
    MaxPooling2D(2,2),

    Conv2D(64,(3,3),activation="relu",padding="same"),
    MaxPooling2D(2,2),

    Conv2D(128,(3,3),activation="relu",padding="same"),
    MaxPooling2D(2,2),

    GlobalAveragePooling2D(),

    Dense(128,activation="relu"),

    Dense(NUM_CLASSES,activation="softmax")

])

basic_cnn.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_5      │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 7)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 331,991 (1.27 MB)

 Trainable params: 110,663 (432.28 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 221,328 (864.57 KB)

In [141]:
basic_cnn.compile(

    optimizer=Adam(learning_rate=0.0005),

    loss="categorical_crossentropy",

    metrics=["accuracy"]

)

In [152]:
history_es = basic_cnn.fit(

    train_generator,

    validation_data=val_generator,

    epochs=5,

    class_weight=class_weights,

    

)

Epoch 1/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 173s 392ms/step - accuracy: 0.4153 - loss: 1.7079 - val_accuracy: 0.4860 - val_loss: 1.2631
Epoch 2/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 170s 386ms/step - accuracy: 0.3787 - loss: 1.6096 - val_accuracy: 0.4534 - val_loss: 1.3256
Epoch 3/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 218s 423ms/step - accuracy: 0.4485 - loss: 1.4965 - val_accuracy: 0.4447 - val_loss: 1.4897
Epoch 4/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 213s 486ms/step - accuracy: 0.4475 - loss: 1.4581 - val_accuracy: 0.5087 - val_loss: 1.2977
Epoch 5/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 183s 416ms/step - accuracy: 0.4633 - loss: 1.4178 - val_accuracy: 0.4867 - val_loss: 1.2919

In [153]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

train_loss, train_acc = basic_cnn.evaluate(train_generator, verbose=0)

val_loss, val_acc = basic_cnn.evaluate(val_generator, verbose=0)

test_loss, test_acc = basic_cnn.evaluate(test_generator, verbose=0)

pred = basic_cnn.predict(test_generator, verbose=0)

pred_labels = np.argmax(pred, axis=1)

true_labels = test_generator.classes

precision = precision_score(
    true_labels,
    pred_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    pred_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    pred_labels,
    average="weighted"
)

In [167]:
comparison_basic_lr = pd.DataFrame({

    "Metric":[
        "Train Accuracy",
        "Validation Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Phase 4":[
        0.480328081,
        0.522436774,
        0.494650699,
        0.438463913,
        0.424650699,
        0.419771229
    ],

    "After LearningRate":[
        train_acc,
        val_acc,
        test_acc,
        precision,
        recall,
        f1
    ]

})

comparison_basic_lr["Improvement"] = (

    comparison_basic_lr["After LearningRate"] -

    comparison_basic_lr["Phase 4"]

)

comparison_basic_lr

                Metric   Phase 4  After LearningRate  Improvement
0       Train Accuracy  0.480328            0.465906    -0.014422
1  Validation Accuracy  0.522437            0.486684    -0.035752
2        Test Accuracy  0.494651            0.475050    -0.019601
3            Precision  0.438464            0.739142     0.300678
4               Recall  0.424651            0.475050     0.050399
5             F1 Score  0.419771            0.527120     0.107349

In [155]:
basic_cnn.save("models2/batch_cnn_lr.keras")

# Optimizer Comparison (SGD, Adam, RMSprop)

In [160]:
#Basic Cnn
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense

basic_cnn = Sequential([

    Conv2D(32, (3,3), activation="relu", padding="same",
           input_shape=(IMG_SIZE, IMG_SIZE,3)),
    MaxPooling2D(2,2),

    Conv2D(64,(3,3),activation="relu",padding="same"),
    MaxPooling2D(2,2),

    Conv2D(128,(3,3),activation="relu",padding="same"),
    MaxPooling2D(2,2),

    GlobalAveragePooling2D(),

    Dense(128,activation="relu"),

    Dense(NUM_CLASSES,activation="softmax")

])

basic_cnn.summary()
basic_cnn.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_5      │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 7)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 331,991 (1.27 MB)

 Trainable params: 110,663 (432.28 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 221,328 (864.57 KB)

In [161]:
from tensorflow.keras.optimizers import SGD
basic_cnn_sg.compile(
    optimizer=SGD(learning_rate=0.001, momentum=0.9),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [163]:
history_sg = basic_cnn_sg.fit(

    train_generator,

    validation_data=val_generator,

    epochs=5,

    class_weight=class_weights,


)

Epoch 1/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 179s 408ms/step - accuracy: 0.3556 - loss: 1.8538 - val_accuracy: 0.6698 - val_loss: 1.5156
Epoch 2/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 188s 427ms/step - accuracy: 0.3452 - loss: 1.8262 - val_accuracy: 0.5266 - val_loss: 1.3855
Epoch 3/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 181s 413ms/step - accuracy: 0.4198 - loss: 1.7472 - val_accuracy: 0.4241 - val_loss: 1.7487
Epoch 4/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 179s 408ms/step - accuracy: 0.4046 - loss: 1.7391 - val_accuracy: 0.3142 - val_loss: 1.7317
Epoch 5/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 195s 444ms/step - accuracy: 0.4153 - loss: 1.7274 - val_accuracy: 0.5007 - val_loss: 1.2824

In [168]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

train_loss, train_acc = basic_cnn_sg.evaluate(train_generator, verbose=0)

val_loss, val_acc = basic_cnn_sg.evaluate(val_generator, verbose=0)

test_loss, test_acc = basic_cnn_sg.evaluate(test_generator, verbose=0)

pred = basic_cnn_sg.predict(test_generator, verbose=0)

pred_labels = np.argmax(pred, axis=1)

true_labels = test_generator.classes

precision = precision_score(
    true_labels,
    pred_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    pred_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    pred_labels,
    average="weighted"
)

In [170]:
comparison_basic_lr = pd.DataFrame({

    "Metric":[
        "Train Accuracy",
        "Validation Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Phase 4":[
        0.480328081,
        0.522436774,
        0.494650699,
        0.438463913,
        0.424650699,
        0.419771229
    ],

    "After SGD":[
        train_acc,
        val_acc,
        test_acc,
        precision,
        recall,
        f1
    ]

})

comparison_basic_lr["Improvement"] = (

    comparison_basic_lr["After SGD"] -

    comparison_basic_lr["Phase 4"]

)

comparison_basic_lr

                Metric   Phase 4  After SGD  Improvement
0       Train Accuracy  0.480328   0.494294     0.013966
1  Validation Accuracy  0.522437   0.500666    -0.021771
2        Test Accuracy  0.494651   0.491018    -0.003633
3            Precision  0.438464   0.647825     0.209361
4               Recall  0.424651   0.491018     0.066367
5             F1 Score  0.419771   0.523106     0.103335

In [171]:
basic_cnn.save("models2/batch_cnn_sg.keras")

# RMSprop

In [172]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    BatchNormalization,
    GlobalAveragePooling2D,
    Dense,
    Dropout
)
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

In [173]:
cnn_model = Sequential([

    # Block 1
    Conv2D(32, (3,3), activation="relu", padding="same",
           kernel_regularizer=l2(0.001), input_shape=(128,128,3)),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    # Block 2
    Conv2D(64, (3,3), activation="relu", padding="same",
           kernel_regularizer=l2(0.001)),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.30),

    # Block 3
    Conv2D(128, (3,3), activation="relu", padding="same",
           kernel_regularizer=l2(0.001)),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.35),

    # Block 4
    Conv2D(256, (3,3), activation="relu", padding="same",
           kernel_regularizer=l2(0.001)),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.40),

    # Classification
    GlobalAveragePooling2D(),

    Dense(256, activation="relu"),
    Dropout(0.50),

    Dense(7, activation="softmax")
])

/home/aximsoft/jupyter-env/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [174]:
optimizer = RMSprop(
    learning_rate=0.0001,
    rho=0.9
)

cnn_model.compile(
    optimizer=optimizer,
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [177]:
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=8,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.2,
    patience=2,
    min_lr=1e-6
)

In [178]:
history = cnn_model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,
    class_weight=class_weights,
    callbacks=[early_stop, reduce_lr]
)

Epoch 1/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 339s 772ms/step - accuracy: 0.3806 - loss: 2.2550 - val_accuracy: 0.1551 - val_loss: 2.5104 - learning_rate: 1.0000e-04
Epoch 2/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 383s 775ms/step - accuracy: 0.4174 - loss: 2.0749 - val_accuracy: 0.4707 - val_loss: 1.7239 - learning_rate: 1.0000e-04
Epoch 3/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 333s 758ms/step - accuracy: 0.4501 - loss: 1.9797 - val_accuracy: 0.5013 - val_loss: 1.6333 - learning_rate: 1.0000e-04
Epoch 4/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 335s 763ms/step - accuracy: 0.4632 - loss: 1.9004 - val_accuracy: 0.5446 - val_loss: 1.4628 - learning_rate: 1.0000e-04
Epoch 5/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 347s 790ms/step - accuracy: 0.4797 - loss: 1.8387 - val_accuracy: 0.5952 - val_loss: 1.4350 - learning_rate: 1.0000e-04
Epoch 6/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 328s 746ms/step - accuracy: 0.4894 - loss: 1.7842 - val_accuracy: 0.6531 - val_loss: 1.2482 - learning_rate: 1.0000e-04
Epoch 7/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 442s 1s/step - accuracy: 0.5026 - loss: 1.7463 - val_accuracy: 0.6771 - val_loss: 1.2288 - learning_rate: 1.0000e-04
Epoch 8/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 363s 826ms/step - accuracy: 0.5111 - loss: 1.7209 - val_accuracy: 0.6485 - val_loss: 1.4075 - learning_rate: 1.0000e-04
Epoch 9/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 342s 775ms/step - accuracy: 0.5074 - loss: 1.6887 - val_accuracy: 0.6791 - val_loss: 1.3963 - learning_rate: 1.0000e-04
Epoch 10/15
439/439 ━━━━━━━━━━━━━━━━━━━━ 335s 763ms/step - accuracy: 0.5381 - loss: 1.6593 - val_accuracy: 0.6791 - val_loss: 1.3415 - learning_rate: 2.0000e-05
Epoch 11/15
301/439 ━━━━━━━━━━━━━━━━━━━━ 2:17 993ms/step - accuracy: 0.5248 - loss: 1.6815

KeyboardInterrupt:

In [179]:
loss, accuracy = cnn_model.evaluate(test_generator)

print("Test Loss :", loss)
print("Test Accuracy :", accuracy)

94/94 ━━━━━━━━━━━━━━━━━━━━ 31s 325ms/step - accuracy: 0.6727 - loss: 1.2586
Test Loss : 1.2586088180541992
Test Accuracy : 0.6726546883583069

In [180]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

train_loss, train_acc = cnn_model.evaluate(train_generator, verbose=0)

val_loss, val_acc = cnn_model.evaluate(val_generator, verbose=0)

test_loss, test_acc = cnn_model.evaluate(test_generator, verbose=0)

pred = basic_cnn_sg.predict(test_generator, verbose=0)

pred_labels = np.argmax(pred, axis=1)

true_labels = test_generator.classes

precision = precision_score(
    true_labels,
    pred_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    pred_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    pred_labels,
    average="weighted"
)

In [181]:
comparison_basic_lr = pd.DataFrame({

    "Metric":[
        "Train Accuracy",
        "Validation Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Phase 4":[
        0.480328081,
        0.522436774,
        0.494650699,
        0.438463913,
        0.424650699,
        0.419771229
    ],

    "After RMSPROP":[
        train_acc,
        val_acc,
        test_acc,
        precision,
        recall,
        f1
    ]

})

comparison_basic_lr["Improvement"] = (

    comparison_basic_lr["After RMSPROP"] -

    comparison_basic_lr["Phase 4"]

)

comparison_basic_lr

                Metric   Phase 4  After RMSPROP  Improvement
0       Train Accuracy  0.480328       0.682311     0.201983
1  Validation Accuracy  0.522437       0.676431     0.153995
2        Test Accuracy  0.494651       0.672655     0.178004
3            Precision  0.438464       0.647825     0.209361
4               Recall  0.424651       0.491018     0.066367
5             F1 Score  0.419771       0.523106     0.103335

In [182]:
cnn_model.save("models2/basic_cnn_rg.keras")

# Batch Size Comparison

In [183]:
#Batch Size Comparison
#Constants

BATCH_SIZE = 32

In [184]:

basic_cnn_batch = load_model(
    "/home/aximsoft/Documents/AximSoft_EOWA/Week_09/models/basic_cnn1.keras"
)

basic_cnn.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_5      │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 7)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 331,991 (1.27 MB)

 Trainable params: 110,663 (432.28 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 221,328 (864.57 KB)

In [185]:
train_ds = tf.data.Dataset.from_tensor_slices(
    (
        train_df["path"],
        train_df["label"]
    )
)
train_ds = train_ds.map(
    preprocess,
    num_parallel_calls=tf.data.AUTOTUNE
)
train_ds = train_ds.shuffle(1000)
train_ds = train_ds.batch(BATCH_SIZE)
train_ds = train_ds.prefetch(
    tf.data.AUTOTUNE
)

In [188]:
valid_ds = tf.data.Dataset.from_tensor_slices(
    (
        valid_df["image_path"],
        valid_df["dx"]
    )
)
valid_ds = valid_ds.map(
    preprocess,
    num_parallel_calls=tf.data.AUTOTUNE
)
valid_ds = valid_ds.batch(BATCH_SIZE)
valid_ds = valid_ds.prefetch(
    tf.data.AUTOTUNE
)

In [205]:
train_datagen = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    width_shift_range=0.1,

    height_shift_range=0.1,

    zoom_range=0.2,

    horizontal_flip=True,

    vertical_flip=True,

    brightness_range=[0.8, 1.2]
)

test_datagen = ImageDataGenerator(

    rescale=1./255)

In [206]:
train_generator = train_datagen.flow_from_dataframe(

    dataframe=train_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=True
)

val_generator = test_datagen.flow_from_dataframe(

    dataframe=val_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=False
)

test_generator = test_datagen.flow_from_dataframe(

    dataframe=test_df,

    x_col="path",

    y_col="label",

    target_size=(IMG_SIZE, IMG_SIZE),

    batch_size=BATCH_SIZE,

    class_mode="categorical",

    shuffle=False
)

Found 7010 validated image filenames belonging to 7 classes.
Found 1502 validated image filenames belonging to 7 classes.
Found 1503 validated image filenames belonging to 7 classes.

In [207]:
early_stop = EarlyStopping(

    monitor="val_loss",

    patience=2,

    restore_best_weights=True,

    verbose=1

)

basic_cnn.compile(

    optimizer=Adam(learning_rate=0.0001),

    loss="categorical_crossentropy",

    metrics=["accuracy"]

)
history_batch = basic_cnn_batch.fit(

    train_generator,

    validation_data=val_generator,

    epochs=5,

    class_weight=class_weights,

    callbacks=[early_stop]

)

Epoch 1/5
220/220 ━━━━━━━━━━━━━━━━━━━━ 165s 747ms/step - accuracy: 0.4418 - loss: 1.7392 - val_accuracy: 0.3602 - val_loss: 1.6544
Epoch 2/5
220/220 ━━━━━━━━━━━━━━━━━━━━ 206s 768ms/step - accuracy: 0.4000 - loss: 1.6257 - val_accuracy: 0.5007 - val_loss: 1.1848
Epoch 3/5
220/220 ━━━━━━━━━━━━━━━━━━━━ 177s 803ms/step - accuracy: 0.4556 - loss: 1.4902 - val_accuracy: 0.4907 - val_loss: 1.2402
Epoch 4/5
220/220 ━━━━━━━━━━━━━━━━━━━━ 178s 806ms/step - accuracy: 0.4586 - loss: 1.4610 - val_accuracy: 0.4973 - val_loss: 1.2217
Epoch 4: early stopping
Restoring model weights from the end of the best epoch: 2.

In [208]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

train_loss, train_acc = basic_cnn_batch.evaluate(train_generator, verbose=0)

val_loss, val_acc =basic_cnn_batch.evaluate(val_generator, verbose=0)

test_loss, test_acc =basic_cnn_batch.evaluate(test_generator, verbose=0)

pred = basic_cnn_sg.predict(test_generator, verbose=0)

pred_labels = np.argmax(pred, axis=1)

true_labels = test_generator.classes

precision = precision_score(
    true_labels,
    pred_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    pred_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    pred_labels,
    average="weighted"
)

In [210]:
comparison_basic_lr = pd.DataFrame({

    "Metric":[
        "Train Accuracy",
        "Validation Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Phase 4":[
        0.480328081,
        0.522436774,
        0.494650699,
        0.438463913,
        0.424650699,
        0.419771229
    ],

    "After Batch":[
        train_acc,
        val_acc,
        test_acc,
        precision,
        recall,
        f1
    ]

})

comparison_basic_lr["Improvement"] = (

    comparison_basic_lr["After Batch"] -

    comparison_basic_lr["Phase 4"]

)

comparison_basic_lr

                Metric   Phase 4  After Batch  Improvement
0       Train Accuracy  0.480328     0.489872     0.009544
1  Validation Accuracy  0.522437     0.500666    -0.021771
2        Test Accuracy  0.494651     0.489022    -0.005629
3            Precision  0.438464     0.647825     0.209361
4               Recall  0.424651     0.491018     0.066367
5             F1 Score  0.419771     0.523106     0.103335

In [211]:
cnn_model.save("models2/basic_cnn_Batchsize.keras")

In [215]:
import sys
print(sys.executable)

/home/aximsoft/jupyter-env/bin/python

In [224]:
import sys
!{sys.executable} -m pip install tensorboard

Collecting tensorboard
  Downloading tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (1.83.0)
Collecting markdown>=2.6.8 (from tensorboard)
  Downloading markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.12.0 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (2.5.1)
Requirement already satisfied: packaging in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (26.2)
Requirement already satisfied: pillow in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from tensorboard) (83.0.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Using cached werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: typing-extensions~=4.12 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in /home/aximsoft/jupyter-env/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 165.8 kB/s  0:00:33 eta 0:00:010:02:10
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 5.8/6.6 MB 234.8 kB/s eta 0:00:04:07
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (5.8 MB/6.6 MB, attempt 1)
Resuming download tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (5.8 MB/6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 242.1 kB/s  0:00:033.8 kB/s eta 0:00:02:04
Downloading markdown-3.10.2-py3-none-any.whl (108 kB)
Using cached werkzeug-3.1.8-py3-none-any.whl (226 kB)
Installing collected packages: werkzeug, tensorboard-data-server, markdown, tensorboard
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [tensorboard][0m 3/4 [tensorboard]data-server]
Successfully installed markdown-3.10.2 tensorboard-2.21.0 tensorboard-data-server-0.7.2 werkzeug-3.1.8

In [23]:
import keras_tuner as kt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam, SGD, RMSprop

IMG_SIZE = 128
NUM_CLASSES = 7

def build_model(hp):

    model = Sequential()

    model.add(
        Conv2D(
            filters=hp.Choice("filters", [32, 64]),
            kernel_size=(3,3),
            activation="relu",
            input_shape=(IMG_SIZE, IMG_SIZE, 3)
        )
    )

    model.add(MaxPooling2D())

    model.add(
        Conv2D(
            filters=hp.Choice("filters2", [64, 128]),
            kernel_size=(3,3),
            activation="relu"
        )
    )

    model.add(MaxPooling2D())

    model.add(Flatten())

    model.add(
        Dense(
            units=hp.Choice("dense_units", [64, 128, 256]),
            activation="relu"
        )
    )

    model.add(Dense(NUM_CLASSES, activation="softmax"))

    lr = hp.Choice("learning_rate", [1e-2, 1e-3, 1e-4])

    optimizer = hp.Choice(
        "optimizer",
        ["adam", "sgd", "rmsprop"]
    )

    if optimizer == "adam":
        opt = Adam(learning_rate=lr)

    elif optimizer == "sgd":
        opt = SGD(learning_rate=lr)

    else:
        opt = RMSprop(learning_rate=lr)

    model.compile(
        optimizer=opt,
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

In [ ]:
tuner = kt.RandomSearch(

    build_model,

    objective="val_accuracy",

    max_trials=5,

    directory="tuner",

    project_name="basic_cnn"

)

In [27]:
tuner.search(

    train_generator,

    validation_data=val_generator,

    epochs=5

)

Trial 5 Complete [00h 32m 37s]
val_accuracy: 0.6711052060127258

Best val_accuracy So Far: 0.7290279865264893
Total elapsed time: 02h 47m 19s

In [28]:
best_hp = tuner.get_best_hyperparameters(1)[0]

print(best_hp.values)

{'filters': 32, 'filters2': 128, 'dense_units': 128, 'learning_rate': 0.0001, 'optimizer': 'rmsprop'}

In [25]:
#BestModel_Basic Cnn
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop

final_basic_cnn = Sequential([

    Conv2D(
        32,
        (3,3),
        activation="relu",
        input_shape=(IMG_SIZE, IMG_SIZE, 3)
    ),

    MaxPooling2D(2,2),

    Conv2D(
        128,
        (3,3),
        activation="relu"
    ),

    MaxPooling2D(2,2),

    Flatten(),

    Dense(
        128,
        activation="relu"
    ),

    Dense(
        NUM_CLASSES,
        activation="softmax"
    )

])

final_basic_cnn.compile(

    optimizer=RMSprop(
        learning_rate=0.0001
    ),

    loss="categorical_crossentropy",

    metrics=["accuracy"]

)

final_basic_cnn.summary()

/home/aximsoft/jupyter-env/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1785388629.230258   36064 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 126, 126, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 61, 61, 128)    │        36,992 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 115200)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │    14,745,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 7)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,784,519 (56.40 MB)

 Trainable params: 14,784,519 (56.40 MB)

 Non-trainable params: 0 (0.00 B)

In [26]:
history_final = final_basic_cnn.fit(

    train_generator,

    validation_data=val_generator,

    epochs=5,

    class_weight=class_weights,

    verbose=1

)

Epoch 1/5

I0000 00:00:1785388642.734462   36064 generator_dataset_op.cc:213] Memory patch applied: M_TRIM_THRESHOLD=128 kb was set.

439/439 ━━━━━━━━━━━━━━━━━━━━ 228s 517ms/step - accuracy: 0.4137 - loss: 1.8914 - val_accuracy: 0.4674 - val_loss: 1.3945
Epoch 2/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 221s 504ms/step - accuracy: 0.4623 - loss: 1.7441 - val_accuracy: 0.5399 - val_loss: 1.2240
Epoch 3/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 232s 528ms/step - accuracy: 0.4819 - loss: 1.6362 - val_accuracy: 0.4507 - val_loss: 1.4742
Epoch 4/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 218s 495ms/step - accuracy: 0.4977 - loss: 1.5464 - val_accuracy: 0.2670 - val_loss: 2.0381
Epoch 5/5
439/439 ━━━━━━━━━━━━━━━━━━━━ 297s 677ms/step - accuracy: 0.5029 - loss: 1.4642 - val_accuracy: 0.5386 - val_loss: 1.1462

In [27]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

train_loss, train_acc = final_basic_cnn.evaluate(train_generator, verbose=0)

val_loss, val_acc =final_basic_cnn.evaluate(val_generator, verbose=0)

test_loss, test_acc =final_basic_cnn.evaluate(test_generator, verbose=0)

pred = final_basic_cnn.predict(test_generator, verbose=0)

pred_labels = np.argmax(pred, axis=1)

true_labels = test_generator.classes

precision = precision_score(
    true_labels,
    pred_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    pred_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    pred_labels,
    average="weighted"
)

In [28]:
final_basic_cnn.save("models2/final_basic_cnn.keras")

In [29]:
print([
        train_acc,
        val_acc,
        test_acc,
        precision,
        recall,
        f1
    ])

[0.5398002862930298, 0.5386151671409607, 0.5262807607650757, 0.7065811939087793, 0.5262807717897539, 0.5773591505720971]

In [ ]:
import pandas as pd

comparison_df = pd.DataFrame({
    "Metric": [
        "Train Accuracy",
        "Validation Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Phase 4": [
        0.480328,
        0.522437,
        0.494651,
        0.438464,
        0.424651,
        0.419771
    ],

    "Early Stopping": [
        0.490328,
        0.472437,
        0.484651,
        1.828464,
        1.774651,
        0.419771
    ],

    "Learning Rate": [
        0.465906,
        0.486684,
        0.475050,
        0.739142,
        0.475050,
        0.527120
    ],

    "SGD": [
        0.494294,
        0.500666,
        0.491018,
        0.647825,
        0.491018,
        0.523106
    ],

    "RMSprop": [
        0.682311,
        0.676431,
        0.672655,
        0.647825,
        0.491018,
        0.523106
    ],

    "Batch Size": [
        0.489872,
        0.500666,
        0.489022,
        0.647825,
        0.491018,
        0.523106
    ],

    "Hyperparameter Tuning": [
        0.539800,
        0.538615,
        0.526281,
        0.706581,
        0.526281,
        0.577359
    ]
})

print(comparison_df)

In [6]:
import pandas as pd

comparison_df = pd.DataFrame({
    "Technique": [
        "Phase 4 (Baseline)",
        "Early Stopping",
        "Learning Rate Scheduling",
        "SGD",
        "RMSprop",
        "Batch Size",
        "Hyperparameter Tuning"
    ],
    
    "Train Accuracy": [
        0.480328,
        0.490328,
        0.465906,
        0.494294,
        0.682311,
        0.489872,
        0.539800
    ],
    
    "Validation Accuracy": [
        0.522437,
        0.472437,
        0.486684,
        0.500666,
        0.676431,
        0.500666,
        0.538615
    ],
    
    "Test Accuracy": [
        0.494651,
        0.484651,
        0.475050,
        0.491018,
        0.672655,
        0.489022,
        0.526281
    ],
    
    "Precision": [
        0.438464,
        1.828464,
        0.739142,
        0.647825,
        0.647825,
        0.647825,
        0.706581
    ],
    
    "Recall": [
        0.424651,
        1.774651,
        0.475050,
        0.491018,
        0.491018,
        0.491018,
        0.526281
    ],
    
    "F1 Score": [
        0.419771,
        0.419771,
        0.527120,
        0.523106,
        0.523106,
        0.523106,
        0.577359
    ]
})
 
comparison_df = comparison_df.sort_values(

    by="Test Accuracy",

    ascending=False

).reset_index(drop=True)
 
comparison_df

,Technique,Train Accuracy,Validation Accuracy,Test Accuracy,Precision,Recall,F1 Score
0,RMSprop,0.682311,0.676431,0.672655,0.647825,0.491018,0.523106
1,Hyperparameter Tuning,0.539800,0.538615,0.526281,0.706581,0.526281,0.577359
2,Phase 4 (Baseline),0.480328,0.522437,0.494651,0.438464,0.424651,0.419771
3,SGD,0.494294,0.500666,0.491018,0.647825,0.491018,0.523106
4,Batch Size,0.489872,0.500666,0.489022,0.647825,0.491018,0.523106
5,Early Stopping,0.490328,0.472437,0.484651,1.828464,1.774651,0.419771
6,Learning Rate Scheduling,0.465906,0.486684,0.475050,0.739142,0.475050,0.527120